projectplay/config/routes.rb
Projectplay::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  
  root :to => 'playgrounds#index'

  resources :playgrounds do
    collection do
      get :addToGooglePlaces
    end
  end

  

end

projectplay/app/models/playground.rb
class Playground < ActiveRecord::Base
  attr_accessible :access, :agelevel, :playclass, :compsum, :conditions,
  :drinkingw, :freeunstruct, :generalcomments, :graspvalue, :intellect,
  :invitation, :mapid, :modsum, :monitoring, :name, :naturualen,
  :openaccess, :physicald, :programming, :restrooms, :safelocation, :seating,
  :socialdom, :specificcomments, :subarea, :totplay, :weather, :lat, :long
end

projectplay/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

projectplay/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

projectplay/app/controllers/playgrounds_controller.rb
require 'net/http'
class PlaygroundsController < ApplicationController
  # GET /playgrounds
  # GET /playgrounds.json
  def index
    @playgrounds = Playground.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @playgrounds }
    end
  end

  def addToGooglePlaces
    # The API key info is stored in an environmental variable for privacy
    # To add env variables to Heroku, use for ex: heroku config:add GPLACES_KEY=8N029N81
    @playgrounds = Playground.all
    url = "https://maps.googleapis.com/maps/api/place/add/json?sensor=false&key=" + ENV['GPLACES_KEY']
    #@playgrounds.each do |p|
    p = @playgrounds.first
    @playground = p
      # Form the json request according to Google Places API:
      # https://developers.google.com/places/documentation/actions#PlaceReports
      json =  { "location" => { "lat" => p.lat, "lng" => p.long}, "accuracy" => 50, "name" => p.name, "types" => ["park"], "language" => "en" }.to_json
      @returninfo = post(url,json)
      @jsonrequest = json
    #end
    # @returninfo will be available to the view 
    
    respond_to do |format|
      format.html # addToGooglePlaces.html.erb
      format.json { render :json => @playgrounds }
    end
  end
=begin
  def requestgp(req)
    res = Net::HTTP.start('maps.googleapis.com', '443') { |http|http.request(req) }
    unless res.kind_of?(Net::HTTPSuccess)
      handle_error(req, res)
    end
    res
  end
=end
  def post(uri, json)
    # this sequence of code must be done for HTTP/SSL/Basic Auth b/c use_ssl must be specified before starting session
    res = ""
    http = Net::HTTP.new('maps.googleapis.com', '443')
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    resp = http.start do |ht|  
      req = Net::HTTP::Post.new(uri)
      req["content-type"] = "application/json"
      req.body = json
      res = ht.request(req)
    end
    res.body
  end

  # GET /playgrounds/1
  # GET /playgrounds/1.json
  def show
    @playground = Playground.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @playground }
    end
  end

  # GET /playgrounds/new
  # GET /playgrounds/new.json
  def new
    @playground = Playground.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @playground }
    end
  end

  # GET /playgrounds/1/edit
  def edit
    @playground = Playground.find(params[:id])
  end

  # POST /playgrounds
  # POST /playgrounds.json
  def create
    @playground = Playground.new(params[:playground])

    respond_to do |format|
      if @playground.save
        format.html { redirect_to @playground, :notice => 'Playground was successfully created.' }
        format.json { render :json => @playground, :status => :created, :location => @playground }
      else
        format.html { render :action => "new" }
        format.json { render :json => @playground.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /playgrounds/1
  # PUT /playgrounds/1.json
  def update
    @playground = Playground.find(params[:id])

    respond_to do |format|
      if @playground.update_attributes(params[:playground])
        format.html { redirect_to @playground, :notice => 'Playground was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @playground.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /playgrounds/1
  # DELETE /playgrounds/1.json
  def destroy
    @playground = Playground.find(params[:id])
    @playground.destroy

    respond_to do |format|
      format.html { redirect_to playgrounds_url }
      format.json { head :no_content }
    end
  end
end

projectplay/app/helpers/application_helper.rb
module ApplicationHelper
end

projectplay/app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

projectplay/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projectplay</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

projectplay/app/views/playgrounds/_form.html.erb
<%= form_for(@playground) do |f| %>
  <% if @playground.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playground.errors.count, "error") %> prohibited this playground from being saved:</h2>

      <ul>
      <% @playground.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :mapid %><br />
    <%= f.number_field :mapid %>
  </div>
  <div class="field">
    <%= f.label :agelevel %><br />
    <%= f.text_field :agelevel %>
  </div>
  <div class="field">
    <%= f.label :totplay %><br />
    <%= f.number_field :totplay %>
  </div>
  <div class="field">
    <%= f.label :openaccess %><br />
    <%= f.number_field :openaccess %>
  </div>
  <div class="field">
    <%= f.label :invitation %><br />
    <%= f.number_field :invitation %>
  </div>
  <div class="field">
    <%= f.label :access %><br />
    <%= f.number_field :access %>
  </div>
  <div class="field">
    <%= f.label :safelocation %><br />
    <%= f.number_field :safelocation %>
  </div>
  <div class="field">
    <%= f.label :conditions %><br />
    <%= f.number_field :conditions %>
  </div>
  <div class="field">
    <%= f.label :monitoring %><br />
    <%= f.number_field :monitoring %>
  </div>
  <div class="field">
    <%= f.label :programming %><br />
    <%= f.number_field :programming %>
  </div>
  <div class="field">
    <%= f.label :weather %><br />
    <%= f.number_field :weather %>
  </div>
  <div class="field">
    <%= f.label :seating %><br />
    <%= f.number_field :seating %>
  </div>
  <div class="field">
    <%= f.label :restrooms %><br />
    <%= f.number_field :restrooms %>
  </div>
  <div class="field">
    <%= f.label :drinkingw %><br />
    <%= f.number_field :drinkingw %>
  </div>
  <div class="field">
    <%= f.label :physicald %><br />
    <%= f.number_field :physicald %>
  </div>
  <div class="field">
    <%= f.label :socialdom %><br />
    <%= f.number_field :socialdom %>
  </div>
  <div class="field">
    <%= f.label :intellect %><br />
    <%= f.number_field :intellect %>
  </div>
  <div class="field">
    <%= f.label :naturualen %><br />
    <%= f.number_field :naturualen %>
  </div>
  <div class="field">
    <%= f.label :freeunstruct %><br />
    <%= f.number_field :freeunstruct %>
  </div>
  <div class="field">
    <%= f.label :specificcomments %><br />
    <%= f.text_area :specificcomments %>
  </div>
  <div class="field">
    <%= f.label :generalcomments %><br />
    <%= f.text_area :generalcomments %>
  </div>
  <div class="field">
    <%= f.label :compsum %><br />
    <%= f.number_field :compsum %>
  </div>
  <div class="field">
    <%= f.label :modsum %><br />
    <%= f.number_field :modsum %>
  </div>
  <div class="field">
    <%= f.label :graspvalue %><br />
    <%= f.number_field :graspvalue %>
  </div>
  <div class="field">
    <%= f.label :class %><br />
    <%= f.text_field :class %>
  </div>
  <div class="field">
    <%= f.label :subarea %><br />
    <%= f.text_area :subarea %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

projectplay/app/views/playgrounds/addToGooglePlaces.html.erb
<p id="notice"><%= notice %></p>

<p> <b>return status from Google Places:</b>
  <%= @returninfo %>
</p>

<p> <b>JSON request to Google Places:</b>
  <%= @jsonrequest %>
</p>

<p>
  <b>Name:</b>
  <%= @playground.name %>
</p>

<p>
  <b>Mapid:</b>
  <%= @playground.mapid %>
</p>

<p>
  <b>Agelevel:</b>
  <%= @playground.agelevel %>
</p>

<p>
  <b>Totplay:</b>
  <%= @playground.totplay %>
</p>

<p>
  <b>Openaccess:</b>
  <%= @playground.openaccess %>
</p>

<p>
  <b>Invitation:</b>
  <%= @playground.invitation %>
</p>

<p>
  <b>Access:</b>
  <%= @playground.access %>
</p>

<p>
  <b>Safelocation:</b>
  <%= @playground.safelocation %>
</p>

<p>
  <b>Conditions:</b>
  <%= @playground.conditions %>
</p>

<p>
  <b>Monitoring:</b>
  <%= @playground.monitoring %>
</p>

<p>
  <b>Programming:</b>
  <%= @playground.programming %>
</p>

<p>
  <b>Weather:</b>
  <%= @playground.weather %>
</p>

<p>
  <b>Seating:</b>
  <%= @playground.seating %>
</p>

<p>
  <b>Restrooms:</b>
  <%= @playground.restrooms %>
</p>

<p>
  <b>Drinkingw:</b>
  <%= @playground.drinkingw %>
</p>

<p>
  <b>Physicald:</b>
  <%= @playground.physicald %>
</p>

<p>
  <b>Socialdom:</b>
  <%= @playground.socialdom %>
</p>

<p>
  <b>Intellect:</b>
  <%= @playground.intellect %>
</p>

<p>
  <b>Naturualen:</b>
  <%= @playground.naturualen %>
</p>

<p>
  <b>Freeunstruct:</b>
  <%= @playground.freeunstruct %>
</p>

<p>
  <b>Specificcomments:</b>
  <%= @playground.specificcomments %>
</p>

<p>
  <b>Generalcomments:</b>
  <%= @playground.generalcomments %>
</p>

<p>
  <b>Compsum:</b>
  <%= @playground.compsum %>
</p>

<p>
  <b>Modsum:</b>
  <%= @playground.modsum %>
</p>

<p>
  <b>Graspvalue:</b>
  <%= @playground.graspvalue %>
</p>

<p>
  <b>Class:</b>
  <%= @playground.class %>
</p>

<p>
  <b>Subarea:</b>
  <%= @playground.subarea %>
</p>


<%= link_to 'Edit', edit_playground_path(@playground) %> |
<%= link_to 'Back', playgrounds_path %>

projectplay/app/views/playgrounds/edit.html.erb
<h1>Editing playground</h1>

<%= render 'form' %>

<%= link_to 'Show', @playground %> |
<%= link_to 'Back', playgrounds_path %>

projectplay/app/views/playgrounds/index.html.erb
	<div style="height=100"></div>
        <div class="ribbon-wrapper">
		<div class="ribbon-front">
                        <br>
			<center><h1>Project Play - Coming Soon</h1></center>
		</div>
		<div class="ribbon-edge-topleft"></div>
		<div class="ribbon-edge-topright"></div>
		<div class="ribbon-edge-bottomleft"></div>
		<div class="ribbon-edge-bottomright"></div>
		<div class="ribbon-back-left"></div>
		<div class="ribbon-back-right"></div>
	</div>

projectplay/app/views/playgrounds/new.html.erb
<h1>New playground</h1>

<%= render 'form' %>

<%= link_to 'Back', playgrounds_path %>

projectplay/app/views/playgrounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @playground.name %>
</p>

<p>
  <b>Mapid:</b>
  <%= @playground.mapid %>
</p>

<p>
  <b>Agelevel:</b>
  <%= @playground.agelevel %>
</p>

<p>
  <b>Totplay:</b>
  <%= @playground.totplay %>
</p>

<p>
  <b>Openaccess:</b>
  <%= @playground.openaccess %>
</p>

<p>
  <b>Invitation:</b>
  <%= @playground.invitation %>
</p>

<p>
  <b>Access:</b>
  <%= @playground.access %>
</p>

<p>
  <b>Safelocation:</b>
  <%= @playground.safelocation %>
</p>

<p>
  <b>Conditions:</b>
  <%= @playground.conditions %>
</p>

<p>
  <b>Monitoring:</b>
  <%= @playground.monitoring %>
</p>

<p>
  <b>Programming:</b>
  <%= @playground.programming %>
</p>

<p>
  <b>Weather:</b>
  <%= @playground.weather %>
</p>

<p>
  <b>Seating:</b>
  <%= @playground.seating %>
</p>

<p>
  <b>Restrooms:</b>
  <%= @playground.restrooms %>
</p>

<p>
  <b>Drinkingw:</b>
  <%= @playground.drinkingw %>
</p>

<p>
  <b>Physicald:</b>
  <%= @playground.physicald %>
</p>

<p>
  <b>Socialdom:</b>
  <%= @playground.socialdom %>
</p>

<p>
  <b>Intellect:</b>
  <%= @playground.intellect %>
</p>

<p>
  <b>Naturualen:</b>
  <%= @playground.naturualen %>
</p>

<p>
  <b>Freeunstruct:</b>
  <%= @playground.freeunstruct %>
</p>

<p>
  <b>Specificcomments:</b>
  <%= @playground.specificcomments %>
</p>

<p>
  <b>Generalcomments:</b>
  <%= @playground.generalcomments %>
</p>

<p>
  <b>Compsum:</b>
  <%= @playground.compsum %>
</p>

<p>
  <b>Modsum:</b>
  <%= @playground.modsum %>
</p>

<p>
  <b>Graspvalue:</b>
  <%= @playground.graspvalue %>
</p>

<p>
  <b>Class:</b>
  <%= @playground.class %>
</p>

<p>
  <b>Subarea:</b>
  <%= @playground.subarea %>
</p>


<%= link_to 'Edit', edit_playground_path(@playground) %> |
<%= link_to 'Back', playgrounds_path %>